Repository 9oormthon-time-capsule/time-capsule-FE, pull requests merged in 2024-12, with the labels that each got.

#16 [FEAT] feat: 타임 캡슐 전체 페이지 연결
  package.json
  src/components/CustomButton.jsx
  src/components/WriteForm.jsx
  src/components/main/CapsuleBox.tsx
  src/components/main/LetterCreateButton.tsx
  src/components/main/LetterMenuOverlay.tsx
  src/layout/MainLayout.tsx
  src/pages/main/MainPage.tsx
  src/pages/timecapsule/Directory.tsx
  src/pages/timecapsule/LetterDetail.jsx
  src/pages/timecapsule/ReflectDetail.jsx
  src/router.tsx
  src/timecapsule/LetterDetailPage1.jsx
  src/timecapsule/LetterDetailPage2.jsx
  yarn.lock
Labels: ✨ FEAT, 🔨 CHORE, 💄 DESIGN, 🎨 STYLE

#17 [UI] design:To-do 카테고리 페이지 구현
  src/components/todo/category/CategoryHeader.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/router.tsx
Labels: 💄 DESIGN

#18 [UI] design: todo 할 일 추가 컴포넌트 UI 구현
  .yarn/install-state.gz
  .yarnrc.yml
  package.json
  src/components/todo/AddTodo.jsx
  src/styles/todo/AddTodo.styles.js
  yarn.lock
Labels: 💄 DESIGN

#24 [CHORE] chore: 파일 구조 통일
  src/components/timecapsule/main/CapsuleBox.tsx
  src/components/timecapsule/main/LetterCreateButton.tsx
  src/components/timecapsule/main/LetterMenuOverlay.tsx
  src/components/timecapsule/main/Menu.tsx
  src/components/timecapsule/write/CustomButton.jsx
  src/components/timecapsule/write/StarsBackgroundWrapper.jsx
  src/components/timecapsule/write/WriteForm.jsx
  src/components/todo/main/AddTodo.jsx
  src/components/todo/main/Calendar.jsx
  src/components/todo/main/TodoHeader.tsx
  src/components/todo/main/TodoMenu.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
  src/pages/timecapsule/directory/Directory.tsx
  src/pages/timecapsule/write/LetterWritePage.jsx
  src/pages/timecapsule/write/ReflectWritePage.jsx
  src/pages/todo/TodoMainPage.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/router.tsx
  src/styles/timecapsule/directory/Directory.style.ts
  src/styles/timecapsule/write/WriteForm.js
  src/styles/timecapsule/write/WritePageStyles.js
  src/styles/todo/category/Category.style.ts
  src/styles/todo/category/CategoryRegister.style.ts
  src/styles/todo/main/AddTodo.styles.js
  src/timecapsule/LetterDetailPage1.jsx
  src/timecapsule/LetterDetailPage2.jsx
Labels: 🔨 CHORE

#26 [CHORE] chore: 스타일 파일명 및 형식 변경
  src/components/timecapsule/write/StarsBackgroundWrapper.jsx
  src/components/timecapsule/write/WriteForm.jsx
  src/pages/timecapsule/write/LetterWritePage.jsx
  src/pages/timecapsule/write/ReflectWritePage.jsx
  src/styles/timecapsule/write/WriteForm.style.ts
  src/styles/timecapsule/write/WritePage.style.ts
  src/styles/todo/main/AddTodo.styles.ts
Labels: 🔨 CHORE

#28 [CHORE/REFACTOR] chore/refactor: 스타일 파일 분리 및 S. 접두어 추가
  src/components/timecapsule/main/CapsuleBox.tsx
  src/components/timecapsule/main/LetterCreateButton.tsx
  src/components/timecapsule/main/LetterMenuOverlay.tsx
  src/components/timecapsule/main/Menu.tsx
  src/components/timecapsule/write/CustomButton.jsx
  src/components/timecapsule/write/StarsBackground.jsx
  src/components/timecapsule/write/WriteButton.jsx
  src/components/timecapsule/write/WriteForm.jsx
  src/components/todo/category/CategoryHeader.tsx
  src/components/todo/main/AddTodo.jsx
  src/components/todo/main/Calendar.jsx
  src/components/todo/main/TodoHeader.tsx
  src/components/todo/main/TodoMenu.tsx
  src/layout/Header.tsx
  src/layout/MainLayout.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
  src/pages/timecapsule/write/LetterWritePage.jsx
  src/pages/timecapsule/write/ReflectWritePage.jsx
  src/pages/todo/TodoMainPage.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/styles/layout/Header.style.ts
  src/styles/layout/MainLayout.style.ts
  src/styles/timecapsule/MainPage.style.ts
  src/styles/timecapsule/detail/LetterDetail.style.ts
  src/styles/timecapsule/detail/ReflectDetail.style.ts
  src/styles/timecapsule/main/CapsuleBox.style.ts
  src/styles/timecapsule/main/LetterCreateButton.style.ts
  src/styles/timecapsule/main/LetterMenuOverlay.style.ts
  src/styles/timecapsule/main/Menu.style.ts
  src/styles/timecapsule/write/CustomBox.style.ts
  src/styles/timecapsule/write/StarsBackground.style.ts
  src/styles/timecapsule/write/WriteForm.style.ts
  src/styles/timecapsule/write/WritePage.style.ts
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/category/Category.style.ts
  src/styles/todo/category/CategoryHeader.style.ts
  src/styles/todo/category/CategoryRegister.style.ts
  src/styles/todo/main/AddTodo.style.ts
  src/styles/todo/main/Calendar.style.ts
  src/styles/todo/main/TodoHeader.style.ts
  src/styles/todo/main/TodoMenu.style.ts
Labels: 🔨 CHORE, ♻️ REFACTOR

#30 [REFACTOR] refactor: Header, Menu 공통 컴포넌트 분리
  src/components/common/Header.tsx
  src/components/common/Menu.tsx
  src/components/timecapsule/main/Menu.tsx
  src/components/todo/main/TodoHeader.tsx
  src/components/todo/main/TodoMenu.tsx
  src/layout/Header.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/todo/TodoMainPage.tsx
  src/styles/common/Header.style.ts
  src/styles/common/Menu.style.ts
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/main/TodoHeader.style.ts
  src/styles/todo/main/TodoMenu.style.ts
Labels: ♻️ REFACTOR

#32 [FEAT] feat: 메뉴 컴포넌트 전체 적용 및 전체 레이아웃 통일
  src/components/common/Header.tsx
  src/components/common/Menu.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/pages/todo/TodoMainPage.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/styles/common/Header.style.ts
  src/styles/common/Menu.style.ts
  src/styles/layout/MainLayout.style.ts
  src/styles/timecapsule/directory/Directory.style.ts
  src/styles/timecapsule/main/LetterCreateButton.style.ts
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/category/Category.style.ts
  src/styles/todo/category/CategoryHeader.style.ts
  src/styles/todo/category/CategoryRegister.style.ts
Labels: ✨ FEAT, ♻️ REFACTOR, 💄 DESIGN
