Repository 9oormthon-time-capsule/time-capsule-FE, pull requests merged in 2025-02, with the labels that each got.

#118 [BUG] fix: 달력에 할 일 개수 실시간 반영되지 않는 오류 및 달력 기능/UI 수정
  src/api/letter.ts
  src/components/todo/main/Calendar.jsx
  src/styles/todo/main/Calendar.style.ts
Labels: 🔥 BUG, ✨ FEAT, 💄 DESIGN

#120 [BUG] fix: 달력 UI/UX 개선
  src/components/todo/main/Calendar.jsx
Labels: 🔥 BUG, 💄 DESIGN

#123 [BUG] fix: 달력에서 월 단위 이상의 선택을 제한하도록 수정
  src/api/letter.ts
  src/api/reflect.ts
  src/components/todo/main/Calendar.jsx
  src/styles/todo/main/Calendar.style.ts
Labels: 🔥 BUG, 🔨 CHORE

#127 [FEAT] feat & design Letter/Reflect Detail 페이지 PDF 다운로드 내용
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
  src/styles/timecapsule/detail/LetterDetail.style.ts
  src/styles/timecapsule/detail/ReflectDetail.style.ts
Labels: ✨ FEAT, 💄 DESIGN

#131 [FEAT] feat: beforeunload 이벤트 리스너 추가하여 새로고침 및 페이지 이탈 방지
  src/pages/timecapsule/write/LetterWritePage.tsx
  src/pages/timecapsule/write/ReflectWritePage.tsx
Labels: ✨ FEAT

#135 [BUG] fix: 카테고리 삭제 시 해당 카테고리의 할 일들도 삭제되도록 수정
  src/pages/todo/category/CategoryPage.tsx
Labels: 🔥 BUG

#139 [UI] design: 메인, 달력, Todo, Header 페이지 레이아웃 및 스타일 전반 수정
  src/components/common/Header.tsx
  src/components/common/Menu.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
  src/components/todo/main/AddTodo.tsx
  src/layout/MainLayout.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/styles/common/Header.style.ts
  src/styles/common/Loading.style.ts
  src/styles/common/Menu.style.ts
  src/styles/layout/MainLayout.style.ts
  src/styles/timecapsule/MainPage.style.ts
  src/styles/timecapsule/directory/Directory.style.ts
  src/styles/timecapsule/main/CapsuleBox.style.ts
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/main/AddTodo.style.ts
  src/styles/todo/main/Calendar.style.ts
Labels: 🔥 BUG, 💄 DESIGN

#141 [UI] design: 카테고리 모달창 UI 변경
  src/components/todo/category/CategoryModal.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/styles/todo/category/CategoryModal.style.ts
Labels: 💄 DESIGN

#144 [FEAT] feat: 로그인되지 않은 사용자의 접근 거부
  src/api/index.ts
  src/components/common/Menu.tsx
  src/components/common/PrivateRoute.tsx
  src/router.tsx
Labels: ✨ FEAT

#146 [REFACTOR] refactor: “/” 라우트로 이동할 때의 UI 개선
  src/components/common/PrivateRoute.tsx
  src/router.tsx
Labels: ♻️ REFACTOR

#147 [BUG] fix: 할 일 다른 날짜 등록 시 정렬 오류
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/components/todo/main/Calendar.jsx
Labels: 🔥 BUG

#149 [REFACTOR] refactor: any 타입을 string 타입으로 변경
  src/pages/login/Auth.ts
Labels: ♻️ REFACTOR

#151 [FEAT] feat: 할 일 수정 기능 구현
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/hooks/useTodo.tsx
  src/styles/todo/main/AddTodo.style.ts
Labels: ✨ FEAT

#154 [FEAT] feat: 편지, 회고 작성 페이지 뒤로가기 기능 구현 및 beforeunload 오류 수정
  src/components/common/Header.tsx
  src/components/timecapsule/write/WriteForm.tsx
  src/components/todo/category/CategoryModal.tsx
  src/pages/timecapsule/write/LetterWritePage.tsx
  src/pages/timecapsule/write/ReflectWritePage.tsx
  src/styles/timecapsule/write/CustomButton.style.ts
  src/styles/timecapsule/write/WritePage.style.ts
Labels: 🔥 BUG, ✨ FEAT, 💄 DESIGN

#155 [UI] design: 달력 레이아웃 변경
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/main/Calendar.style.ts
Labels: 💄 DESIGN

#159 [BUG] fix: 할 일 체크박스 클릭 시 내용이 사라지는 오류 수정
  src/components/todo/main/AddTodo.tsx
Labels: 🔥 BUG

#160 [BUG] fix: 달력 레이아웃 버그 수정
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/main/Calendar.style.ts
Labels: 🔥 BUG

#163 [UI] design: 회고작성페이지 이모지 선택 UI 수정
  src/pages/timecapsule/write/ReflectWritePage.tsx
  src/styles/timecapsule/write/WritePage.style.ts
Labels: ♻️ REFACTOR, 💄 DESIGN

#165 [UI] design: 편지, 회고 상세 페이지 UI 및 데이터 처리 개선
  src/api/directoryLetter.ts
  src/components/timecapsule/directory/Capsules.tsx
  src/hooks/useLetterData.tsx
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
  src/pages/timecapsule/directory/Directory.tsx
  src/styles/timecapsule/detail/LetterDetail.style.ts
  src/styles/timecapsule/detail/ReflectDetail.style.ts
Labels: ♻️ REFACTOR, 💄 DESIGN

#167 [REFACTOR] refactor: 할 일 페이지 데이터 로딩 상태 개선 및 카테고리 레이아웃 수정
  src/components/todo/main/AddTodo.tsx
  src/components/todo/main/Calendar.jsx
  src/pages/timecapsule/detail/LetterDetail_BACKUP_1483.jsx
  src/pages/timecapsule/detail/LetterDetail_BASE_1483.jsx
  src/pages/timecapsule/detail/LetterDetail_LOCAL_1483.jsx
  src/pages/timecapsule/detail/LetterDetail_REMOTE_1483.jsx
  src/pages/todo/TodoMainPage.tsx
  src/styles/todo/category/Category.style.ts
  src/styles/todo/category/CategoryHeader.style.ts
  src/styles/todo/category/CategoryModal.style.ts
  src/styles/todo/category/CategoryRegister.style.ts
  src/styles/todo/main/Calendar.style.ts
Labels: ♻️ REFACTOR, 💄 DESIGN

#170 [REFACTOR] refactor: 메인화면 데이터 처리 개선, 로딩 상태 및 오류 수정
  src/api/letter.ts
  src/components/timecapsule/directory/Capsules.tsx
  src/context/EmotionContext.tsx
  src/context/EmotionProvider.tsx
  src/hooks/useUser.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
  src/pages/timecapsule/directory/Directory.tsx
Labels: 🔥 BUG, ♻️ REFACTOR

#171 [FEAT] feat: 회원 탈퇴 모달 구현
  src/components/common/Header.tsx
  src/components/common/Menu.tsx
  src/components/common/Modal.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
  src/styles/common/Modal.style.ts
Labels: ✨ FEAT

#173 [REFACTOR] refactor: Todo 낙관적 업데이트 적용
  src/hooks/useTodo.tsx
Labels: ♻️ REFACTOR
