Repository 9oormthon-time-capsule/time-capsule-FE, pull requests merged in 2025-01, with the labels that each got.

#34 feat: 카카오 간편 로그인 구현
  .gitignore
  .prettierrc.json
  src/pages/login/Auth.ts
  src/pages/login/Login.tsx
  src/router.tsx
Labels: ✨ FEAT

#39 [FEAT] feat: 편지 보관 개수 api 연결
  public/main/Box-1.png
  public/main/Box-2.png
  public/main/Box-3.png
  public/main/Box-4.png
  src/api/letter.ts
  src/components/timecapsule/main/CapsuleBox.tsx
  src/pages/timecapsule/MainPage.tsx
Labels: ✨ FEAT

#41 [REFACTOR] refactor: 유저ID 동적 경로 구조 변경
  src/components/common/Menu.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/store/userStore.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#43 [FEAT] feat: Todo 카테고리 api 연결
  src/api/category.ts
  src/api/letter.ts
  src/components/todo/category/CategoryHeader.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/store/userStore.ts
  src/styles/todo/category/Category.style.ts
  src/styles/todo/category/CategoryRegister.style.ts
Labels: ✨ FEAT

#46 [FEAT] feat: 편지 작성 API 연결
  src/api/letter.ts
  src/components/timecapsule/write/WriteForm.jsx
  src/pages/timecapsule/write/LetterWritePage.jsx
  yarn.lock
Labels: ✨ FEAT

#48 [REFACTOR] refactor: 카테고리 관리 예외처리
  src/api/category.ts
  src/pages/todo/category/CategoryPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/styles/todo/category/Category.style.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#50 [FEAT] feat: 라우팅 경로 변경 및 사용자 api 구조 수정
  src/api/user.ts
  src/components/common/Menu.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/router.tsx
  src/store/userStore.ts
Labels: ✨ FEAT, ♻️ REFACTOR

#52 [FEAT] feat: 회고 작성 API 연결
  src/api/reflect.ts
  src/components/timecapsule/write/WriteForm.jsx
  src/pages/timecapsule/write/ReflectWritePage.jsx
Labels: 🔥 BUG, ✨ FEAT

#53 [UI] design: 메인페이지 UI 구현
  public/main/Capsule.svg
  public/main/Menu.svg
  src/components/common/Header.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
  src/components/timecapsule/main/LetterCreateButton.tsx
  src/pages/timecapsule/MainPage.tsx
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/styles/common/Header.style.ts
  src/styles/common/Menu.style.ts
  src/styles/layout/MainLayout.style.ts
  src/styles/timecapsule/MainPage.style.ts
  src/styles/timecapsule/directory/Directory.style.ts
  src/styles/timecapsule/main/CapsuleBox.style.ts
  src/styles/timecapsule/main/LetterCreateButton.style.ts
  src/styles/timecapsule/main/LetterMenuOverlay.style.ts
Labels: ♻️ REFACTOR, 💄 DESIGN

#55 [FEAT] feat: 타임 캡슐 보관함 페이지 API 연결
  src/api/directoryLetter.ts
  src/components/timecapsule/directory/Capsules.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/pages/timecapsule/directory/directoryButtonUtil.ts
Labels: ✨ FEAT

#58 [UI] design: 달력 UI 수정
  package.json
  src/components/todo/main/Calendar.jsx
  src/styles/todo/TodoMainPage.style.ts
  src/styles/todo/main/Calendar.style.ts
  yarn.lock
Labels: 💄 DESIGN

#56 [FEAT] feat: todo 카테고리 선택 시 input창 토글 기능 구현
  src/components/todo/main/AddTodo.jsx
  src/components/todo/main/AddTodo.tsx
  src/styles/todo/main/AddTodo.style.ts
Labels: ✨ FEAT

#60 [FEAT] feat: Todo API 연결 및 항목 관리 기능 구현
  src/api/category.ts
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/styles/todo/main/AddTodo.style.ts
Labels: ✨ FEAT

#63 [UI] design: 카테고리 삭제 모달창 구현
  src/components/todo/category/CategoryDeleteModal.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/styles/todo/category/CategoryModal.style.ts
Labels: ✨ FEAT, 💄 DESIGN

#69 [UI] design: 메뉴 레이아웃 조정 및 카테고리 UI 수정
  src/pages/todo/category/CategoryRegisterPage.tsx
  src/styles/common/Menu.style.ts
  src/styles/todo/category/Category.style.ts
  src/styles/todo/main/AddTodo.style.ts
Labels: 💄 DESIGN

#71 [UI] design: 편지와 회고 작성 페이지 UI 수정
  src/components/timecapsule/write/StarsBackground.tsx
  src/components/timecapsule/write/WriteButton.jsx
  src/components/timecapsule/write/WriteButton.tsx
  src/components/timecapsule/write/WriteForm.tsx
  src/pages/timecapsule/write/LetterWritePage.tsx
  src/pages/timecapsule/write/ReflectWritePage.tsx
  src/styles/timecapsule/write/CustomBox.style.ts
  src/styles/timecapsule/write/CustomButton.style.ts
  src/styles/timecapsule/write/StarsBackground.style.ts
  src/styles/timecapsule/write/WriteForm.style.ts
  src/styles/timecapsule/write/WritePage.style.ts
Labels: 🔨 CHORE, 💄 DESIGN

#72 [BUG] fix: 편지 보관함 경로 수정
  src/components/common/Menu.tsx
  src/components/timecapsule/main/CapsuleBox.tsx
Labels: 🔥 BUG

#74 [FEAT] feat: 편지 작성 제한 기능 추가
  src/api/letter.ts
  src/components/timecapsule/main/LetterMenuOverlay.tsx
Labels: ✨ FEAT

#76 [FEAT] feat: 타임캡슐 읽기 가능 여부 확인 기능 구현
  src/api/letter.ts
  src/components/timecapsule/directory/Capsules.tsx
Labels: ✨ FEAT

#78 [BUG] fix: 회고 작성 후 보관함 페이지에서 타임 캡슐이 보이는 버그 수정
  src/pages/timecapsule/directory/Directory.tsx
  src/router.tsx
Labels: 🔥 BUG

#80 [FEAT] feat: 사용자 로그아웃 구현
  src/components/common/Menu.tsx
Labels: ✨ FEAT

#83 [FEAT] feat: 유저 회원 탈퇴 기능 구현
  src/components/common/Menu.tsx
Labels: 🔥 BUG, ✨ FEAT

#85 [FEAT] feat: 타임캡슐 상세 페이지 API 연결
  src/pages/timecapsule/detail/LetterDetail.jsx
  src/pages/timecapsule/detail/ReflectDetail.jsx
Labels: ✨ FEAT

#88 [FEAT] feat: 해당 날짜에 맞게 투두 리스트 필터링 기능 구현
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/components/todo/main/Calendar.jsx
  src/pages/todo/TodoMainPage.tsx
  src/styles/todo/main/Calendar.style.ts
Labels: ✨ FEAT

#87 [REFACTOR] refactor: API URL .env 파일로 이동
  src/api/category.ts
  src/api/directoryLetter.ts
  src/api/index.ts
  src/api/letter.ts
  src/api/reflect.ts
  src/api/todo.ts
  src/api/user.ts
  src/components/common/Menu.tsx
Labels: 🔥 BUG, 🌎 DEPLOY, ♻️ REFACTOR

#91 [UI] design: 헤더 메뉴 비율 조정
  src/components/common/Menu.tsx
  src/pages/timecapsule/directory/Directory.tsx
  src/styles/common/Header.style.ts
  src/styles/common/Menu.style.ts
  src/styles/timecapsule/directory/Directory.style.ts
Labels: ♻️ REFACTOR, 💄 DESIGN

#94 [UI] design: 글작성 버튼 오버레이 클릭 이벤트 추가
  src/components/timecapsule/main/LetterCreateButton.tsx
  src/components/timecapsule/main/LetterMenuOverlay.tsx
Labels: 💄 DESIGN

#103 [BUG] fix: 할 일 연속 추가 시 중복 등록되는 오류 수정
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/hooks/useTodo.tsx
Labels: 🔥 BUG, ✨ FEAT

#107 [BUG] fix: Todo 등록 시 선택한 날짜에 맞게 저장되도록 수정
  src/api/todo.ts
  src/components/todo/main/AddTodo.tsx
  src/components/todo/main/Calendar.jsx
  src/hooks/useTodo.tsx
  src/pages/todo/TodoMainPage.tsx
Labels: 🔥 BUG

#110 [FEAT] feat: 카테고리 수정 기능 추가
  src/api/category.ts
  src/components/todo/category/CategoryDeleteModal.tsx
  src/components/todo/category/CategoryModal.tsx
  src/pages/todo/category/CategoryPage.tsx
  src/styles/todo/category/CategoryModal.style.ts
Labels: ✨ FEAT, 💄 DESIGN
